import os
import textwrap
from typing import List


class CompatShimGenerator:
    def __init__(self, repo_path: str):
        self.repo_path = os.path.abspath(repo_path)

    def generate_shim(
        self, original_module_path: str, new_module_path: str, symbols: List[str] = None
    ) -> str:
        """
        Generates a shim file at original_module_path that imports from new_module_path.
        """
        if not symbols:
            # Import *
            import_st = f"from {new_module_path} import *"
        else:
            import_st = f"from {new_module_path} import {', '.join(symbols)}"

        content = textwrap.dedent(f"""
        # Compatibility Shim generated by SAGUARO
        # Redirects {original_module_path} -> {new_module_path}
        
        import warnings
        
        def _warn():
            warnings.warn(
                "{original_module_path} is deprecated. Use {new_module_path} instead.",
                DeprecationWarning,
                stacklevel=2
            )
            
        _warn()
        
        {import_st}
        
        # Re-export for wildcard imports if needed
        # __all__ = [...] 
        """).strip()

        return content

    def apply_shim(self, file_path: str, new_target: str, symbols: List[str] = None):
        """Writes the shim to disk."""
        content = self.generate_shim(os.path.basename(file_path), new_target, symbols)
        with open(file_path, "w") as f:
            f.write(content)
